apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cleanup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]