apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cleanup
subjects:
  - kind: ServiceAccount
    name: k8s-cleanup
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-cleanup
  apiGroup: rbac.authorization.k8s.io