apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-cleanup
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - name: k8s-cleanup
              args:
                - Error
              image: ghcr.io/jlehtimaki/k8s-cleanup:latest
              imagePullPolicy: Always
          restartPolicy: Never
          serviceAccountName: k8s-cleanup
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
